apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: amq-broker-sample
  namespace: amq
spec:
  acceptors:
    - anycastPrefix: jms.queue.
      expose: true
      multicastPrefix: /topic/
      name: all
      port: 61616
      protocols: openwire
      sniHost: localhost
  addressSettings: {}
  adminPassword: topSecret
  adminUser: amq
  console:
    expose: true
  deploymentPlan:
    size: 1
    podSecurity: {}
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    readinessProbe: {}
    messageMigration: false
    extraMounts: {}
    managementRBACEnabled: true
    livenessProbe: {}
    journalType: nio
    image: placeholder
    storage:
      size: 4Gi
  upgrades:
    enabled: false
    minor: false
