apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: amq-broker-sample
  namespace: amq
spec:
  acceptors:
    - anycastPrefix: jms.queue.
      expose: true
      multicastPrefix: /topic/
      name: all
      port: 61616
      protocols: openwire
      sniHost: localhost
  deploymentPlan:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    storage:
      size: 4Gi
    size: 1
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    image: placeholder
  addressSettings:
    addressSetting:
      - match: '#'
        deadLetterAddress: DLQ
        maxDeliveryAttempts: 5
        redeliveryDelay: 500
  console:
    expose: true
  upgrades:
    enabled: false
    minor: false
  adminPassword: topSecret
  adminUser: amq
